---
- hosts: all
  become: yes
  tasks:
  - name: 
    ansible.builtin.git:
      repo: https://github.com/iamraviteja18/ansible-learnings.git
      dest: /trail/git
      single_branch: yes
      version: main
