---
- hosts: all
  roles:
    - andrewrothstein.maven
    - jetune.gradle
    - remyma.springboot
    - andrewrothstein.openjdk
    - andrewrothstein.alpine-glibc-shim
    - andrewrothstein.unarchive-deps
